### ISSUE TITLE
toDecimal() doesn't add decimal point and/or trailing zeros

### ISSUE THREAD

**Issue by willnwhite** [peterolson/BigRational.js#23]
`bigRat(9).toDecimal(2) => "9"`
I'm expecting `bigRat(9).toDecimal(2) => "9.00"`
(and I guess `bigRat(9).toDecimal(0) => "9"`)

**Comment by willnwhite** [comment]
```
var string = bigRat(9).toDecimal(decimals);
if (!string.includes(".")) {
  string = string.concat(".00");
} else if (string.includes(".") && string.split(".")[1].length === 1) {
  string = string.concat((decimals - 1) * "0");
}
return string;
```

**Comment by peterolson** [comment]
This was intentional. If a number can be represented exactly in the given number of decimal digits, it will remove any trailing `0`s since they don't provide any information. Otherwise, it will keep them. For example,

 - `bigRat(9).toDecimal(2)` => `"9"`
 - `bigRat("9.0001").toDecimal(2)` => `"9.00"`

If this doesn't seem like sensible behavior, let me know. In any case, I should probably mention these details in the documentation.

**Comment by willnwhite** [comment]
I'm not sure. I think toDecimal reminds me of "to decimal places", and I'm sure (at school) if I was asked to give 9 to 2 decimal places, I would say 9.00.

**Comment by willnwhite** [comment]
You were dead right. I should have said I am trying to represent money, and at the time I couldn't see a use for toDecimal other than printing for display. This should be a function separate to toDecimal() if anything.
