### ISSUE TITLE
make bigRat(10,3).toDecimal() => ["3.3333333333", true]

### ISSUE THREAD

**Issue by willnwhite** [peterolson/BigRational.js#24]
I don't want to represent a recurring number without a "...", and toDecimal can't tell me if there were any digits after the cut-off. I guess what I'm asking for is a boolean from toDecimal to say if there were any numbers after the cut-off, and if true I can use that to add a "...".

**Comment by willnwhite** [comment]
In the meantime I guess I could do toDecimal(x) and toDecimal(x+1) and see if there's any difference in length.

**Comment by peterolson** [comment]
This is kind of a special use-case, I'm not sure if it's worth baking in to the `toDecimal` method.

Since you mentioned recurring numbers, do you mean you want to check whether or not the number has a finite decimal representation? If so, you will need to check if the denominator has any prime divisors other than 2 and 5.

**Comment by willnwhite** [comment]
Thanks, this is exactly what I want. I will try to write a function to check this if one doesn't exist.
